name: CI

on: [push, pull_request]
jobs:
  # This task builds the dev image used to build reopt.
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell || 'sh' }}
    strategy:
      matrix:
        include:
        - name: Ubuntu
          os: ubuntu-latest
        - name: MacOS
          os: macos-latest
       # - name: Windows
       #   os: windows-latest
       #   shell: msys2 {0}
      # complete all jobs
      fail-fast: false
    steps:
    - name: Install MSYS2 (Windows)
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        path-type: inherit
        install: curl unzip make mingw-w64-x86_64-gcc mingw-w64-x86_64-gmp
    - name: Install Elan (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        curl -sSL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh > elan-init.sh
        ./elan-init.sh -y
        cygpath -w "$USERPROFILE/.elan/bin" >> $GITHUB_PATH
    - name: Install Elan (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        curl -sSL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh > elan-init.sh
        chmod +x elan-init.sh
        ./elan-init.sh -y
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
    - name: Install Elan (MacOS)
      if: matrix.os == 'macOS-latest'
      run: brew install elan
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache build
      uses: actions/cache@v2
      with:
        path: build
        key: ${{ matrix.name }}-build
    - name: Cache lean_packages
      uses: actions/cache@v2
      with:
        path: lean_packages
        key: ${{ matrix.name }}-lean_packages
    - name: Run AES test
      run: |
        lake build aes_test
        ./build/bin/aes_test ./tests/aes/aes.test
    - name: Run tests
      run: ./scripts/test.sh
